class ColorMap:
    def __init__(self, rgba_dict):
        self.bg = rgba_dict["background"]
        self.fg = rgba_dict["foreground"]
        self.black = rgba_dict["color0"]
        self.blue = rgba_dict["color4"]
        self.green = rgba_dict["color2"]
        self.cyan = rgba_dict["color6"]
        self.red = rgba_dict["color1"]
        self.purple = rgba_dict["color5"]
        self.yellow = rgba_dict["color3"]
        self.lblue = rgba_dict["color12"]
        self.lgreen = rgba_dict["color10"]
        self.lcyan = rgba_dict["color14"]
        self.lred = rgba_dict["color9"]
        self.lpurple = rgba_dict["color14"]
        self.lyellow = rgba_dict["color11"]
        self.lgray = rgba_dict["color7"]
